name    'openstackci-yum'
version '0.1.0'
source  'http://git.openstack.org/cgit/openstack-infra/puppet-yum/'
author  'Dan Prince'
license 'Apache License 2.0'
summary 'Create lightweight Yum repositories'
description 'Puppet module to help manage/create lightweight Yum repositories'
project_page 'https://launchpad.net/openstack-infra'

dependency 'puppetlabs-apache', '>= 0.0.4'
